[phases.setup]
# نثبت بايثون + كولوراما + سوكات من nix مباشرة
nixPkgs = ["python311", "python311Packages.colorama", "socat"]

[start]
# نشغّل السكربت عبر socat على بورت 9000
cmd = "socat -d -d TCP-LISTEN:9000,fork,reuseaddr,crnl EXEC:\"python3 -u ./server.py\",pty,setsid,ctty"
